package com.ecommerce.notification_service.entity;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_STATUS_UPDATED,
    PAYMENT_SUCCESS,
    ORDER_SHIPPED,
    PRODUCT_CREATED,
    PROMOTION,
    SELLER_APPLICATION_APPROVED,
    SELLER_APPLICATION_REJECTED,
    AD_CAMPAIGN_APPROVED,
    AD_CAMPAIGN_REJECTED,
    ACCOUNT_BANNED,
    SYSTEM_ALERT,
    REPORT_RESOLVED,
    USER_WARNED
}
