server:
  port: 8084

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${DB_NAME:cart_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false